// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwsbpjQfIT9D-3e7vQ5x4ocKPUS5POtM',
    appId: '1:574650636830:android:5a91322abb8e1d5013ec0f',
    messagingSenderId: '574650636830',
    projectId: 'chat-28bcb',
    databaseURL: 'https://chat-28bcb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-28bcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY4sojqv36Y16X-XaXQI71RYL0HATNoqE',
    appId: '1:574650636830:ios:d8b5ee975a6e465113ec0f',
    messagingSenderId: '574650636830',
    projectId: 'chat-28bcb',
    databaseURL: 'https://chat-28bcb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-28bcb.appspot.com',
    iosClientId: '574650636830-3nkq2gpemir916k0i3pqg9rvkk6p29jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.printer',
  );
}
